### ISSUE TITLE
Build balls look terrible

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/dark-theme-plugin#100]
(I'm allowed to write that as the author of https://github.com/jenkinsci/jenkins/pull/3997 😁 )

Unfortunately, the screen shot in that PR would look like this with Dark Theme:

> <img width="892" alt="Screenshot" src="https://user-images.githubusercontent.com/1831569/85206450-83d11880-b322-11ea-82ab-657399a6df5c.png">

At the very least, these should animate opacity and not a white overlay.

**Comment by fqueiruga** [comment]
I think this is a difficult one that should be solve by using meaningful icons instead of balls.
