### ISSUE TITLE
Form loading overlay is too bright

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/dark-theme-plugin#101]
While a form is loading, an overlay disabling access to the elements in shown. This is too bright in Jenkins 2.241 with Dark Theme 0.0.3:

> <img width="2014" alt="Screenshot" src="https://user-images.githubusercontent.com/1831569/85206517-f9d57f80-b322-11ea-86b2-74fe6bc8f28c.png">

<details>
<summary>Animation</summary>

> ![Video](https://user-images.githubusercontent.com/1831569/85328039-4d390080-b4d0-11ea-8f3b-43d1bc503b05.gif)

**Comment by timja** [comment]
This was fixed at some point
