### ISSUE TITLE
Github [github-branch-source plugin] uses dark icons

### ISSUE THREAD

**Issue by fred-vogt** [jenkinsci/dark-theme-plugin#104]
Really loving this dark theme.

Problem: `github-branch-source` plugin has icon PNGs that don't work well with dark backgrounds.
 
The images (PNGs) are using a dark foreground color (branch / repo icons):
* https://github.com/jenkinsci/github-branch-source-plugin/tree/master/src/main/webapp/images
* https://github.com/jenkinsci/github-branch-source-plugin/tree/master/src/images

## Github Multi-branch pipeline sidebar
![jenkins-github-sidebar-01-2020-06-20 14-38-41](https://user-images.githubusercontent.com/1837107/85212064-eb2ba000-b303-11ea-8121-02f90f8adbfc.png)
* https://github.com/jenkinsci/github-branch-source-plugin/blob/master/src/main/webapp/images/24x24/github-repo.png
```html
<img src="/static/8a67aafe/plugin/github-branch-source/images/24x24/github-repo.png" alt="" style="width: 24px; height: 24px; " class="icon-github-repo icon-md">
```

## Github Multi-branch pipeline parent job icon
![jenkins-github-mbpj-01- 2020-06-20 14-41-31](https://user-images.githubusercontent.com/1837107/85212090-33e35900-b304-11ea-98fa-cc666b76a905.png)
* https://github.com/jenkinsci/github-branch-source-plugin/blob/master/src/main/webapp/images/48x48/github-repo.png
```html
<img src="/static/8a67aafe/plugin/github-branch-source/images/48x48/github-repo.png" width="48" alt="GitHub Repository" tooltip="GitHub Repository" height="48" title="GitHub Repository">
```

## Github Multi-branch pipeline child job github icon
![jenkins-github-mbpj-02-2020-06-20 14-43-12](https://user-images.githubusercontent.com/1837107/85212120-786ef480-b304-11ea-8478-88922029ffba.png)
* https://github.com/jenkinsci/github-branch-source-plugin/blob/master/src/main/webapp/images/24x24/github-branch.png
```html
<img src="/static/8a67aafe/plugin/github-branch-source/images/24x24/github-branch.png" alt="" style="width: 24px; height: 24px; " class="icon-github-branch icon-md">
```

**Comment by timja** [comment]
It now uses SVGs, see https://ci.jenkins.io which is running it
