### ISSUE TITLE
Cloud statistics is too bright 

### ISSUE THREAD

**Issue by timja** [jenkinsci/dark-theme-plugin#108]
![image](https://user-images.githubusercontent.com/21194782/85390621-fb7c8e80-b540-11ea-8ab2-f23c60cd983c.png)

cc @olivergondza

**Comment by olivergondza** [comment]
Oh, I can imagine. Please let me know if there is something cloud-stats plugin can do to integrate better with theme plugins.

**Comment by timja** [comment]
Resolved in https://github.com/jenkinsci/cloud-stats-plugin/pull/87
