### ISSUE TITLE
Theme does not apply on Jenkins ver. 2.235.1 

### ISSUE THREAD

**Issue by clemans** [jenkinsci/dark-theme-plugin#111]
**Steps to reproduce issue:**
* Installed [Simple Theme Plug-in](https://plugins.jenkins.io/simple-theme-plugin/)
* Tried all of the following URLs to Jenkins -> Manage Jenkins -> Configure System -> Theme -> CSS URL: 
- https://cdn.jsdelivr.net/gh/jenkinsci/dark-theme@latest/src/main/resources/io/jenkins/plugins/darktheme/theme.css
- https://cdn.jsdelivr.net/gh/jenkinsci/dark-theme@latest/src/main/resources/io/jenkins/plugins/darktheme/theme-system.css
- https://cdn.jsdelivr.net/gh/jenkinsci/dark-theme@0.0.3/src/main/resources/io/jenkins/plugins/darktheme/theme.css
- https://cdn.jsdelivr.net/gh/jenkinsci/dark-theme@0.0.3/src/main/resources/io/jenkins/plugins/darktheme/theme-system.css
* Click Apply 
* Refresh and confirm theme not changed
* Tried each CSS URL separately and multiple CSS URLs; no difference

**Troubleshooting steps taken:**
* Verified 0.0.1 & 0.0.2 no longer exists when browsing.
* Verified other CSS themes work:  [Neo2](https://tobix.github.io/jenkins-neo2-theme/dist/neo-light.css) & [Atlassion](https://github.com/djonsson/jenkins-atlassian-theme)

**System information:**
- Docker container using [jenkins/jenkins:latest](https://hub.docker.com/layers/jenkins/library/jenkins/latest/images/sha256-cd14cecfdb3a657ba7d05bea026e7ac8b9abafc6e5c66253ab327c7211fa6281?context=explore)
- Running configuration in a [nginx reverse proxy](https://github.com/nginx-proxy/nginx-proxy) setup
- Configuration is behind a reverse proxy (e.g. https://jenkins.my-domain.io)
- Configuration is a publicly accessible domain name site with binded TLS LetsEncrypt certificate

**Comment by timja** [comment]
See the readme it requires 2.239

**Comment by clemans** [comment]
@timja Huge oversight on my side, my apologies.
