### ISSUE TITLE
jenkins/war - Breadcrumbs header bar items flash a light colored background when clicked

### ISSUE THREAD

**Issue by fred-vogt** [jenkinsci/dark-theme-plugin#126]
![jenkins-breadcrumb-mouseover-01](https://user-images.githubusercontent.com/1837107/88466572-9fc85c80-ce82-11ea-9bdb-f99f43e3c9fd.png)

The color seen in a screen capture is grey - `#c8cec2`.

This is minor, but noticeable.

**Comment by fqueiruga** [comment]
This PR on jenkins core fixes it https://github.com/jenkinsci/jenkins/pull/4867

**Comment by timja** [comment]
Woo thanks @fqueiruga!, I'll try test it out soon.

**Comment by timja** [comment]
@fqueiruga I just tried it out and it doesn't seem to fix this?

**Comment by fqueiruga** [comment]
I'll look into it

**Comment by fqueiruga** [comment]
You're right. Should work now:

<img width="1131" alt="Captura de pantalla 2020-07-31 a las 9 31 28" src="https://user-images.githubusercontent.com/5738588/89011480-b4887280-d310-11ea-82ea-32e79b2da429.png">

**Comment by timja** [comment]
Yup it does, tested it locally, thanks!

**Comment by timja** [comment]
Fixed in https://github.com/jenkinsci/jenkins/pull/4867
