### ISSUE TITLE
Empty folder screen

### ISSUE THREAD

**Issue by timja** [jenkinsci/dark-theme-plugin#128]
![image](https://user-images.githubusercontent.com/21194782/88819023-55631a80-d1b7-11ea-80b0-4e2ae55c27ff.png)

**Comment by fqueiruga** [comment]
How can I access this folder to test this out?

**Comment by timja** [comment]
Install the cloudbees-folder plugin.

New item => Folder

**Comment by res0nance** [comment]
This is actually https://github.com/jenkinsci/branch-api-plugin/blob/master/src/main/resources/jenkins/branch/MultiBranchProjectEmptyView/main.jelly

**Comment by timja** [comment]
https://github.com/jenkinsci/branch-api-plugin/pull/240

**Comment by fqueiruga** [comment]
Do we need to do something on this plugin after the branch-api change has been released?

**Comment by timja** [comment]
no nothing
