### ISSUE TITLE
Credentials popup screen

### ISSUE THREAD

**Issue by timja** [jenkinsci/dark-theme-plugin#129]
![image](https://user-images.githubusercontent.com/21194782/88819097-6e6bcb80-d1b7-11ea-850b-7cfaaa698085.png)

**Comment by fqueiruga** [comment]
I think this should be solved on core. These are YUI styles for modals, so maybe the fix can be put on https://github.com/jenkinsci/jenkins/blob/master/war/src/main/less/base/yui-compatibility.less

**Comment by VirtualTim** [comment]
I suspect the fix is similar to the one here: https://github.com/jenkinsci/jenkins/pull/4931/files

**Comment by timja** [comment]
Yes most likely

**Comment by zbynek** [comment]
Should be fixed in https://github.com/jenkinsci/credentials-plugin/pull/500 (so maybe this issue can be closed)

**Comment by timja** [comment]
> Should be fixed in [jenkinsci/credentials-plugin#500](https://github.com/jenkinsci/credentials-plugin/pull/500) (so maybe this issue can be closed)

just ping when that's released and we can close here

**Comment by zbynek** [comment]
Released in https://github.com/jenkinsci/credentials-plugin/releases/tag/1337.v60b_d7b_c7b_c9f
