### ISSUE TITLE
please consider the blue / red in the bell count admin monitors area

### ISSUE THREAD

**Issue by jsoref** [jenkinsci/dark-theme-plugin#137]
![image](https://user-images.githubusercontent.com/2119212/89562421-ef464b00-d7e7-11ea-9efe-bc1c7e0bf553.png)

**Comment by timja** [comment]
More details:

![image](https://user-images.githubusercontent.com/21194782/89581973-c2b62180-d82f-11ea-983e-489052582574.png)

**Comment by timja** [comment]
Appears to have been fixed at some point:

<img width="81" alt="image" src="https://github.com/user-attachments/assets/fbef5e2d-e69c-4433-8aca-36b397b885ac">

The different states all look better now
