### ISSUE TITLE
Scrollspy tab hover color is not themeable

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/dark-theme-plugin#143]
Appears in a "modern" (Jenkins 2.0 style) configuration form:

> ![Screenshot](https://user-images.githubusercontent.com/1831569/90336076-ad808600-dfd9-11ea-8721-2d73dab01298.png)

**Comment by zbynek** [comment]
@daniel-beck your screenshot is from freestyle job config which no longer has that component. Is this still an issue somewhere in core?

**Comment by timja** [comment]
Pretty sure it was fully ripped out everywhere
