### ISSUE TITLE
Can't download the plugin (404)

### ISSUE THREAD

**Issue by VirtualTim** [jenkinsci/dark-theme-plugin#149]
Don't know what happened here, but the download button in Jenkins requests https://updates.jenkins.io/download/plugins/dark-theme/0.0.10/dark-theme.hpi, which returns a 404.

**Comment by timja** [comment]
There was a Jenkins infra outage last night, we managed to get it back up and running but any plugins released yesterday need manual intervention 

I’ll fix it this morning

**Comment by timja** [comment]
Fixed
