### ISSUE TITLE
Changeset message has light background

### ISSUE THREAD

**Issue by monstrfolk** [jenkinsci/dark-theme-plugin#152]
On git commit changes page, the changeset-message element has background #eed.

<img width="991" alt="Screen Shot 2020-11-27 at 12 33 15 AM" src="https://user-images.githubusercontent.com/3935847/100428021-392d9800-3048-11eb-9e1e-8716e3ff021f.png">

**Comment by oleg-nenashev** [comment]
CC @MarkEWaite

**Comment by NotMyFault** [comment]
This issue can likely be closed, I've updated the changeset look in core which is treated better by now:
![](https://i.imgur.com/F5fqnfJ.png)
