### ISSUE TITLE
404 - theme-dark/theme-system.css not found

### ISSUE THREAD

**Issue by pespinel** [jenkinsci/dark-theme-plugin#153]
I am getting the following error: 

`GET https://XXX/theme-dark/theme-system.css net::ERR_ABORTED 404 (Not Found)`

![Captura de pantalla 2021-01-12 a las 14 13 12](https://user-images.githubusercontent.com/37797002/104319141-c0dc4280-54e0-11eb-921f-83c850d275c1.png)
![Captura de pantalla 2021-01-12 a las 14 19 01](https://user-images.githubusercontent.com/37797002/104319454-2cbeab00-54e1-11eb-964f-6e4609ad2a24.png)

Jenkins version: 2.263.1 LTS
Plugin version: 0.0.10 (Configured via Theme-Manager)

**Comment by timja** [comment]
Normally means your Jenkins system url is not configured right, if you check the network tab does the url look right?

**Comment by pespinel** [comment]
> Normally means your Jenkins system url is not configured right, if you check the network tab does the url look right?

Yes, theme-system.css is the only resource returning 404:

![Captura de pantalla 2021-01-12 a las 15 41 41](https://user-images.githubusercontent.com/37797002/104329252-04d54480-54ed-11eb-8fc0-78b9d60e1b92.png)
![Captura de pantalla 2021-01-12 a las 15 41 16](https://user-images.githubusercontent.com/37797002/104329257-06067180-54ed-11eb-90d9-baa36d43fa4c.png)

**Comment by timja** [comment]
Can you try with this pre-release version of theme manager plugin? https://repo.jenkins-ci.org/incrementals/io/jenkins/plugins/theme-manager/0.6-rc46.ae3fbdaf920e/theme-manager-0.6-rc46.ae3fbdaf920e.hpi

**Comment by pespinel** [comment]
> Can you try with this pre-release version of theme manager plugin? https://repo.jenkins-ci.org/incrementals/io/jenkins/plugins/theme-manager/0.6-rc46.ae3fbdaf920e/theme-manager-0.6-rc46.ae3fbdaf920e.hpi

Actually, i can't. I am not a maintainer in this Jenkins instance ... sorry :(

**Comment by pespinel** [comment]
@timja Do you think that this error could be related? 

![Captura de pantalla 2021-01-13 a las 12 52 59](https://user-images.githubusercontent.com/37797002/104449116-62759980-559e-11eb-97b4-7ec3406a213b.png)

**Comment by timja** [comment]
Unlikely, but this is most likely a mis-configuration issue,

Check the system configuration and make sure the Jenkins URL is set to the right value.

For a working system you can see it on https://ci.jenkins.io/

**Comment by pespinel** [comment]
> Unlikely, but this is most likely a mis-configuration issue,
> 
> Check the system configuration and make sure the Jenkins URL is set to the right value.
> 
> For a working system you can see it on https://ci.jenkins.io/

![Captura de pantalla 2021-01-13 a las 13 37 52](https://user-images.githubusercontent.com/37797002/104453449-b84d4000-55a4-11eb-8181-240e404da314.png)
![Captura de pantalla 2021-01-13 a las 13 39 02](https://user-images.githubusercontent.com/37797002/104453452-ba170380-55a4-11eb-9a48-086f9fdf7fbc.png)

**Comment by timja** [comment]
and is that correct?

**Comment by pespinel** [comment]
> and is that correct?

I think so, if not ... other resources would return 404, right?

**Comment by pespinel** [comment]
@timja Should i move this issue to the [theme_manager_plugin](https://github.com/jenkinsci/theme-manager-plugin/issues) repo?

**Comment by timja** [comment]
as far as I can tell it's a configuration issue but without the hostnames and full request details I can't tell.

If you could just replace bits with mycompany that you want to hide that would help

I need a request for a regular CSS assert / image and one for the dark theme one

**Comment by pespinel** [comment]
I've just realized that the rest of css files are requested from the static directory:

`https://mycompany/static/87d250f9/css/color.css`

While the theme-system.css is requested from this url:

`https://mycompany/theme-dark/theme-system.css`

![Captura de pantalla 2021-01-14 a las 13 56 32](https://user-images.githubusercontent.com/37797002/104593701-56f2a300-5670-11eb-83f6-7d1d01b3b42b.png)

If I append the static directory I can access to the theme-system.css file:

`https://mycompany/static/87d250f9/theme-dark/theme-system.css`

![Captura de pantalla 2021-01-14 a las 13 56 05](https://user-images.githubusercontent.com/37797002/104593718-5e19b100-5670-11eb-99e4-ec4c983e285d.png)

**Comment by timja** [comment]
can you skip your nginx and request the url directly from Jenkins?

**Comment by pespinel** [comment]
> can you skip your nginx and request the url directly from Jenkins?

How? Running wget from a job to this url?

`127.0.0.1/theme-dark/theme-system.css`

**Comment by timja** [comment]
assuming your job runs on the controller yes that would work, it normally runs on port 8080.

or your admin can ssh onto the VM / docker container / pod / w/e and do it

**Comment by pespinel** [comment]
I was able to reproduce it setting up a local instance.

If I set up the Jenkins address to localhost (The default) the css is served correctly. If I change localhost for the private IP the css returns 404.

**Comment by timja** [comment]
it needs to match the url, I've released https://github.com/jenkinsci/theme-manager-plugin/releases/tag/theme-manager-0.6 which probably works around your configuration issue

**Comment by pespinel** [comment]
Same result with 0.6 version of theme-manager :(

**Comment by timja** [comment]
I can't really help any more, I need a way to reproduce this.

At this point it's most likely an issue with your nginx config but hard to say.

**Comment by pespinel** [comment]
I know that it's really hard to figure it out without having maintainer access to the instance, I really appreciate your help!

Do you suggest any other test that I can do?

**Comment by timja** [comment]
ask for the nginx configuration and see if you can re-produce it locally?

**Comment by jdupont** [comment]
I have a problem that feels very similar after updating to v0.0.10 of the dark theme plugin and v0.6 of theme manager. `theme.css` fails to load:

![image](https://user-images.githubusercontent.com/4589387/104821661-6ce89b00-580b-11eb-9a3b-b1925a15a0d3.png)

It is the only resource with a failure. All other resources load fine, but I noticed they use the Jenkins system url exactly as set in System Configuration:

![image](https://user-images.githubusercontent.com/4589387/104821694-9f929380-580b-11eb-91bf-4a5f9319f9d9.png)

![image](https://user-images.githubusercontent.com/4589387/104821720-ccdf4180-580b-11eb-8882-5a325d49f538.png)

I do not use nginx (we're behind haproxy) and I _think_ everything is configured correctly as far as system URLs. I also have extended-choice installed on this Jenkins instance. I think this is likely a bug as everything was working fine prior to the upgrade. Please let me know if there is anything I can do to help provide information for troubleshooting.

**Comment by timja** [comment]
I suspect that you aren't passing through X-Forwarded-* headers properly and Jenkins isn't aware of the correct request URL to build, we changed from using the configured url to the URL that jenkins receives on the backend.

**Comment by jdupont** [comment]
That is entirely possible. Let me double-check our haproxy settings and confirm whether or not we're forwarding that information.

Out of curiosity -- what is the benefit of this change? Why would the URL that the client sends be "more correct" than the one in Jenkins configuration?

**Comment by timja** [comment]
> Out of curiosity -- what is the benefit of this change? Why would the URL that the client sends be "more correct" than the one in Jenkins configuration?

It wouldn't be but some people mis-configure it and this is normally more accurate =/

Also useful if you're accessing it on a different URL for whatever reason, normally if you're bypassing your reverse proxy for whatever reason

**Comment by jdupont** [comment]
Ah OK that makes sense. So I double-checked and I think we have haproxy configured to attach `X-Forward-For` -- we've got [`option forwardfor except 127.0.0.0/8`](https://access.redhat.com/solutions/3552581) set in our config which I believe is the standard way of including that in haproxy (I'm far from an expert on this area though).

Which specific `X-Forwarded-*` header is being looked at? I believe the haproxy option above covers `X-Forwarded-For` only.

**Comment by timja** [comment]
I expect:

* X-Forwarded-Host
* X-Forwarded-Proto

**Comment by jdupont** [comment]
Yup -- those were both missing from our haproxy settings. I added them in and everything seems to be working again.

I'm a big fan of dark theme. Thanks very much for all of your hard work and for your help troubleshooting the above.
