### ISSUE TITLE
Cron Triggers warnings table is not rendered well in administrative warnings

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/dark-theme-plugin#154]
SlowTriggerAdminMonitor uses standard types in https://github.com/jenkinsci/jenkins/blob/8c6327f4c6777d135e374e3d507ba9c20820bfc6/core/src/main/resources/hudson/triggers/SlowTriggerAdminMonitor/message.groovy . It leads to a pretyt bad rendering within the warnings pane

![image](https://user-images.githubusercontent.com/3000480/105167445-03bd9c00-5b19-11eb-8f4a-3a5229a9db08.png)

**Comment by timja** [comment]
the table font colour is set by:
https://github.com/jenkinsci/jenkins/blob/master/war/src/main/less/modules/panes-and-bigtable.less#L19

we could override that in the alerts with something more specific, probably can just go in core rather than here I think

**Comment by timja** [comment]
Fixed most likely by https://github.com/jenkinsci/jenkins/commit/c37613ef3cdb6b3a4a566fa4b47cf1eafeac3ef1 or https://github.com/jenkinsci/jenkins/pull/9115:

Tested with:

```groovy

import hudson.triggers.*

def am = ExtensionList.lookupSingleton(SlowTriggerAdminMonitor.class)

am.report(TimerTrigger.DescriptorImpl.class, "upstream-free", 50000L)
am.report(SCMTrigger.DescriptorImpl.class, "upstream-free", 1000000L)

println am.errors.size()
  
```

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/49bb5a5c-9857-46e9-b004-e9ac35f8d99d">
