### ISSUE TITLE
Warnings are unreadable in Dark Theme

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/dark-theme-plugin#155]
Not a good look for the default theme installed on ci.jenkins.io to not show warnings linked from PR build statuses:

<img width="3472" alt="Screenshot 2021-01-21 at 00 21 56" src="https://user-images.githubusercontent.com/1831569/105253146-2d111300-5b7f-11eb-8116-9e72524fa2c7.png">
<img width="3472" alt="Screenshot 2021-01-21 at 00 22 03" src="https://user-images.githubusercontent.com/1831569/105253152-2edad680-5b7f-11eb-86fa-b3b38f1222e5.png">

**Comment by timja** [comment]
Fixed: https://ci.jenkins.io/job/Plugins/job/matrix-auth-plugin/job/master/109/maven-warnings/
