### ISSUE TITLE
Translation Assistance plugin is not compatible with Dark Theme

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/dark-theme-plugin#159]
[Translation Assistance plugin](https://plugins.jenkins.io/translation/) is no longer useful due to the service deprecation, but it has some use-cases like local instance update. The configuration form does not work well with Dark Theme

![image](https://user-images.githubusercontent.com/3000480/113768264-ef546d00-971f-11eb-8eb0-53172ac1868f.png)

### Version report

Jenkins and plugins versions report: 

* Jenkins 2.277.1
* Translation Assistance Plugin 1.16

**Comment by NotMyFault** [comment]
It's better now, but I would vouch for wontfix, because the plugin is dead and I'm/we're currently investigating into different translation tools to supersede this plugin:
![](https://i.imgur.com/uRgAzY2.png)
