### ISSUE TITLE
"Executor starvation" icon doesn't look good in dark theme

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/dark-theme-plugin#162]
### Version report

Jenkins and plugins versions report:

https://ci.jenkins.io/ with Jenkins 2.289.1

### Reproduction steps

Do not have enough agents

### Results

Expected result:

Executor starvation icon looks good

Actual result:

<img width="512" alt="Screenshot 2021-06-10 at 10 53 43" src="https://user-images.githubusercontent.com/1831569/121495736-26722380-c9da-11eb-8843-f7f5eb76491f.png">

**Comment by timja** [comment]
Seems to have been replaced with another icon at some point:

![image](https://user-images.githubusercontent.com/21194782/136109995-24314cf1-d660-4d4f-b93b-0e0d78e311c4.png)
