### ISSUE TITLE
Powershell quoted strings hard to read due to red color over black background

### ISSUE THREAD

**Issue by thiago-destro** [jenkinsci/dark-theme-plugin#163]
### Feature Request

When writting a quoted string on powershell script plugin using the darktheme, this string will be on red color with a black background, which makes it really difficult to read.
Maybe those strings could have another color to easify the reading?

Thanks!

**Comment by thiago-destro** [comment]
![image](https://user-images.githubusercontent.com/85556827/125422793-70c5e429-3375-4517-8e7b-7be574144818.png)

**Comment by NotMyFault** [comment]
Quoted strings are now colored dark green, much more readable, looks like we can close this?

**Comment by timja** [comment]
FTR:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/21194782/162632371-1f86ca70-a2b4-4187-8509-a4e12434df9a.png">
