### ISSUE TITLE
theme.css is loaded over HTTP (Causes Jenkins to default to white theme.)

### ISSUE THREAD

**Issue by jacobamey** [jenkinsci/dark-theme-plugin#164]
### Description
We utilize HSTS on our domain and serve all content over HTTPS. It seems the style sheet for `Dark-Theme` is served only over HTTP. This causes the browser to drop it as it does not have an HTTPS alternative making the theme unusable when over HTTPS where HTTPS is enforced.

### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.289.3
OS: Linux - 3.10.0-1160.36.2.el7.x86_64

dark-theme:0.0.12
theme-manager:0.6
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
CentOS 7
OS: Linux - 3.10.0-1160.36.2.el7.x86_64
```

### Reproduction steps

- Step 1 Access Jenkins over HTTPS where HSTS is required for the domain used.
- Step 2 Utilizing developer tools review the errors check box to see the dropping of theme.css

![dark-theme-over-https](https://user-images.githubusercontent.com/3608280/129938076-c93c303f-5af3-4827-95b8-d84f2bc7ed25.png)

### Results

Expected result: See and use Jenkins with a Dark Theme.

Actual result: Jenkins defaults to a white (Bright) theme

**Comment by timja** [comment]
That means Jenkins thinks your server is running on http, read up on X-Forwarded-Proto and ensure it’s set for your reverse proxy

**Comment by jacobamey** [comment]
> That means Jenkins thinks your server is running on http, read up on X-Forwarded-Proto and ensure it’s set for your reverse proxy

Ah! thanks, that was enough to steer me in the right direction. I have it all set on my end now!
