### ISSUE TITLE
Different styles for highlighting followed 

### ISSUE THREAD

**Issue by nimishbongale** [jenkinsci/dark-theme-plugin#19]
I'm leaving a screenshot here to show that onhover of the mouse there's a different border highlighting taking place for different items.

![jenkins1](https://user-images.githubusercontent.com/43414361/83146958-a3ef2c80-a114-11ea-9356-670407781ec9.PNG)

I ran the preview run, however, its the same in both cases. 

The list items get highlighted with a white background whereas for some other list items present in the page, its a different highlighting scheme.

The grey background for the "Jenkins" menu has nearly the same colour as the text. Not really sure how it can be bettered.

**Comment by timja** [comment]
Thanks! Confirmed bug.

**Comment by oleg-nenashev** [comment]
Thank you for this contribution! It is much appreciated.

Are you doing it as a part of the [Jenkins UI/UX Hackfest](https://www.jenkins.io/events/online-hackfest/2020-uiux/)? If so, please consider reporting this contribution [here](https://github.com/jenkinsci/ui-ux-hackfest-2020/issues/new/choose) so that we could facilitate reviews and share the story 👍

**Comment by nimishbongale** [comment]
@oleg-nenashev 

Yes, will do!

I contributed towards the documentation for a few other repos, thought I'd add in everything togther!

**Comment by oleg-nenashev** [comment]
Whatever works. Multiple issues are also fine

**Comment by oleg-nenashev** [comment]
@all-contributors please add @nimishbongale for testing

**Comment by timja** [comment]
This will be fixed by https://github.com/jenkinsci/jenkins/pull/4757

**Comment by timja** [comment]
(It was mostly fixed by the above but there's still one highlighting issue that was missed)

**Comment by timja** [comment]
These have been iterated a few times over the years and this was fixed at some point
