### ISSUE TITLE
warnings-ng issue tables not themeable

### ISSUE THREAD

**Issue by strangelookingnerd** [jenkinsci/dark-theme-plugin#213]
![image](https://user-images.githubusercontent.com/49242855/177747829-0108354c-53ea-4953-b98f-0495210559f9.png)

* Text in odd rows is unreadable.
* Hover Text is unreadable for both odd and even rows.

The root cause may not lie in the theme but somewhere else so maybe other components are affected as well.

**Comment by timja** [comment]
cc @uhafner

**Comment by uhafner** [comment]
This is already tracked as https://issues.jenkins.io/browse/JENKINS-68677

The other new UI changes need to be integrated there as well

**Comment by strangelookingnerd** [comment]
Thanks for the feedback. I did not see the issue.

**Comment by asteele0** [comment]
Also having a similar issue.

The alternating table rows aren't readable:
![image](https://user-images.githubusercontent.com/76005161/198151702-5c8fb756-decc-4733-898b-315f2b3aed32.png)
