### ISSUE TITLE
[JENKINS-62496] - Arrow icons don't work well

### ISSUE THREAD

**Issue by timja** [jenkinsci/dark-theme-plugin#24]
Arrows are invisible as they are black in most cases:

![image](https://user-images.githubusercontent.com/21194782/83157742-d9d3e700-a0fb-11ea-85ee-fdeb49744e84.png)

See https://issues.jenkins-ci.org/browse/JENKINS-62496

It would be good to change them to use CSS in core instead

**Comment by fqueiruga** [comment]
Maybe a solution could be to create the caret using CSS, like the dropdown button styles on `buttons.less`
