### ISSUE TITLE
Odd highlighting of operators in `<pre>` tags

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/dark-theme-plugin#257]
Originally discovered on the design library's page of [validation](https://weekly.ci.jenkins.io/design-library/Validation/), operators are highlighted oddly:
![Screenshot 2022-08-23 at 19 32 00](https://user-images.githubusercontent.com/13383509/186225966-963f8b96-172c-462c-8b25-fa2e415f545c.png)

**Comment by NotMyFault** [comment]
Looks like it's coming from here:

![Screenshot 2022-08-23 at 19 37 38](https://user-images.githubusercontent.com/13383509/186227034-cee174f5-0ed3-406a-9a95-b8a82431efec.png)

Deactivating restores the intended design, I guess?
![Screenshot 2022-08-23 at 19 38 19](https://user-images.githubusercontent.com/13383509/186227151-3754e403-ef6d-44f4-8933-80b7dba76ef5.png)

**Comment by timja** [comment]
Not really to do with this plugin I think?

I have some unfinished work to make this better

**Comment by zbynek** [comment]
Looks OK now
