### ISSUE TITLE
Lack of grey colors when using the extended read perms plugin to access the plugin manager

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/dark-theme-plugin#258]
https://user-images.githubusercontent.com/13383509/186774909-2d2b7da3-6289-4967-97d0-91bb8f2c8eb6.mp4

The button above looks like it's clickable, but the actor can't use it, because they have read-only access granted by the extended read perms plugin.

The switch should look like the example below, displayed if a plugin is a dependency of another plugin to visualize that you can't disable it.
![Screenshot 2022-08-25 at 23 49 09](https://user-images.githubusercontent.com/13383509/186775108-1376f150-96c8-4069-8d64-931c4abb808d.png)

**Comment by timja** [comment]
Nothing to do with dark theme its a core bug, I raised a PR anyway at: https://github.com/jenkinsci/jenkins/pull/9463
