### ISSUE TITLE
Black font color in Dark Theme makes text unreadable

### ISSUE THREAD

**Issue by KiraResari** [jenkinsci/dark-theme-plugin#280]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows 10

### Reproduction steps

1. Enable the Dark Theme in the user settings (Built-in Themes > Theme >Dark )

### Expected Results

The dark theme should come on, and the font should be a readable color, e.g. white.

### Actual Results

The dark theme comes on, but the font color is black, rendering any text unreadable unless actively highlighted. I have a screenshot, but for some reason GitHub doesn't let me upload it.

### Anything else?

We're using CloudBees CI Client Controller 2.319.3.4-rolling

**Comment by KiraResari** [comment]
![2022-10-27 Cloudbees Dark Theme Fail](https://user-images.githubusercontent.com/28697173/198937424-d293226c-593f-493d-aabc-eaa5feb9ae4d.png)
Here's the screenshot

**Comment by timja** [comment]
Please fill out the Jenkins and plugin versions report.

Details on how to is here:
https://github.com/jenkinsci/dark-theme-plugin/issues/new?assignees=&labels=bug&template=1-report-bug.yml

At least the dark theme version and the Jenkins version

**Comment by KiraResari** [comment]
Jenkins: 2.319.3.4
OS: Linux - 5.3.18-150300.59.63-default
---
ace-editor:1.1
ant:1.13
apache-httpcomponents-client-4-api:4.5.13-1.0
artifactory:3.15.1
async-http-client:1.7.24.3
authentication-tokens:1.4
aws-credentials:1.32
aws-java-sdk:1.11.995
aws-java-sdk-ec2:1.12.131-302.vbef9650c6521
aws-java-sdk-minimal:1.12.131-302.vbef9650c6521
basic-branch-build-strategies:1.3.2
blueocean-commons:1.25.2
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-4
bouncycastle-api:2.25
branch-api:2.7.0
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-administrative-monitors:1.0.2
cloudbees-analytics:1.39
cloudbees-assurance:2.276.0.9
cloudbees-bitbucket-branch-source:746.v350d2781c184
cloudbees-blueocean-default-theme:0.8
cloudbees-casc-client:1.47
cloudbees-casc-items-api:1.13
cloudbees-folder:6.17
cloudbees-folders-plus:3.26
cloudbees-github-reporting:1.25
cloudbees-groovy-view:1.14
cloudbees-ha:4.35
cloudbees-jenkins-advisor:3.3.2
cloudbees-jsync-archiver:5.21
cloudbees-license:9.62
cloudbees-monitoring:2.13
cloudbees-nodes-plus:1.22
cloudbees-platform-common:1.14
cloudbees-platform-data:1.25
cloudbees-plugin-usage:2.11
cloudbees-ssh-slaves:2.16
cloudbees-support:3.28
cloudbees-template:4.52
cloudbees-uc-data-api:4.48
cloudbees-unified-ui:1.19
cloudbees-view-creation-filter:1.8
cloudbees-workflow-template:3.14
cloudbees-workflow-ui:2.6
command-launcher:1.6
config-file-provider:3.8.2
configuration-as-code:1.55.1
copyartifact:1.46.2
credentials:1055.v1346ba467ba1
credentials-binding:1.27.1
dark-theme:156.v6cf16af6f9ef
deploy:1.16
display-url-api:2.3.5
docker-commons:1.19
docker-java-api:3.1.5.2
docker-plugin:1.2.6
docker-workflow:1.28
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-2
email-ext:2.86
font-awesome-api:5.15.4-5
git:4.10.3
git-client:3.11.0
git-parameter:0.9.15
git-server:1.10
github:1.34.1
github-api:1.301-378.v9807bd746da5
github-branch-source:2.11.4
gradle:1.37.1
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
http_request:1.16
infradna-backup:3.38.48
ivy:2.1
jackson2-api:2.13.1-246.va8a9f3eaf46a
javadoc:1.6
javax-activation-api:1.2.0-3
javax-mail-api:1.6.2-5
jaxb:2.3.0.1
jdk-tool:1.5
jjwt-api:0.11.2-9.c8b45b8bb173
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
kubernetes:3546.v6103d89542d6
kubernetes-client-api:5.11.2-182.v0f1cf4c5904e
kubernetes-credentials:0.9.0
ldap:2.7
mailer:408.vd726a_1130320
mapdb-api:1.0.9.0
matrix-project:1.20
maven-plugin:3.16
metrics:4.0.2.8.1
momentjs:1.1.1
msbuild:1.30
nectar-license:8.38
nectar-rbac:5.66
node-iterator-api:1.5.1
okhttp-api:3.14.9-20211029
operations-center-agent:2.319.0.3
operations-center-client:2.319.0.4
operations-center-cloud:2.319.0.3
operations-center-context:2.319.0.8
pipeline-build-step:2.15.1
pipeline-graph-analysis:188.v3a01e7973f2c
pipeline-input-step:427.va6441fa17010
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.20
pipeline-stage-step:291.vf0a8a7aeeb50
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.20
pipeline-utility-steps:2.10.0
plain-credentials:1.7
plugin-util-api:2.10.0
popper-api:1.16.1-2
popper2-api:2.11.0-1
publish-over:0.22
publish-over-cifs:0.16
ranorex-integration:1.0.2
resource-disposer:0.16
scm-api:2.6.5
script-security:1118.vba21ca2e3286
snakeyaml-api:1.29.1
sqlplus-script-runner:2.0.19
ssh-credentials:1.19
ssh-slaves:1.806.v2253cedd3295
ssh-steps:2.0.0
sshd:3.1.0
structs:308.v852b473a2b8c
support-core:2.80
teamscale-upload:1.4.6
theme-manager:0.6
token-macro:267.vcdaea6462991
trilead-api:1.0.13
user-activity-monitoring:1.4
variant:1.4
workflow-aggregator:2.5
workflow-api:1136.v7f5f1759dc16
workflow-basic-steps:2.24
workflow-cps:2648.2651.v230593e03e9f
workflow-cps-checkpoint:2.11
workflow-cps-global-lib:552.554.vdba55efb9e88
workflow-durable-task-step:1121.va_65b_d2701486
workflow-job:1145.v7f2433caa07f
workflow-multibranch:696.698.v9b4218eea50f
workflow-scm-step:2.13
workflow-step-api:622.vb_8e7c15b_c95a_
workflow-support:804.vba10a18a1476
ws-cleanup:0.40

**Comment by timja** [comment]
Please update all plugins and use the latest LTS.

I missed the reply here but it will be because of outdated plugins
