### ISSUE TITLE
Dark mode does not activate

### ISSUE THREAD

**Issue by 69pankaj69** [jenkinsci/dark-theme-plugin#293]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu latest 22

### Reproduction steps

ddadad

### Expected Results

Dark mode does not activate

### Actual Results

Dark mode does not activate

**Comment by PedroHeenrique** [comment]
See how your browser, or operating system is configured regarding the theme, the documentation says the following (Respect OS/Browser configuration), I was having the same problem, I use Opera GX , I just changed the browser theme to dark and the plugin worked again. I believe the plugin takes into account the browser and/or system settings.
