### ISSUE TITLE
Build History Chart seems to be not compatible

### ISSUE THREAD

**Issue by EstherAF** [jenkinsci/dark-theme-plugin#33]
Not sure if this is a bug, or it has been left in this color intentionally, but the color of the chart seems too light for the theme.

![Screenshot_20200528_212540](https://user-images.githubusercontent.com/5547479/83184805-49f96180-a12a-11ea-99b6-d773f965242b.png)

Testing with:

- jenkins-core at branch timja/dark-mode (jenkinsci/jenkins@86c0bd0)
- dark-theme at master (commit f31189f)

**Comment by timja** [comment]
This widget was removed in https://github.com/jenkinsci/jenkins/pull/6869 (Jenkins 2.431)
