### ISSUE TITLE
Dark Theme does not appear well

### ISSUE THREAD

**Issue by eliaquimmauricio** [jenkinsci/dark-theme-plugin#331]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows Server

### Reproduction steps

I'm trying to use dark theme in Jenkins, but it doesn't work well :(

![image](https://user-images.githubusercontent.com/50126889/220141237-eb40bd37-0ce9-40b0-b5ec-08331d7c2898.png)

![image](https://user-images.githubusercontent.com/50126889/220141452-c01232e9-d1a3-48c3-9db6-5c74be32af2c.png)

### Expected Results

I'd like to see Jenkins with the same tutorial appereance .

![image](https://user-images.githubusercontent.com/50126889/220141920-11481c90-feb2-48ab-9ca9-4cb050c8e72f.png)

### Actual Results

Jenkins with a differente appereance.

**Comment by timja** [comment]
Which version of Jenkins are you using?  

theme.css no longer exists in this repository as we build it using sass.

You should install dark theme as a plugin

**Comment by eliaquimmauricio** [comment]
Hello, I'm using 2.375.3 version.

I tried to use dark theme as a plugin, but it didn't make any change at appereance and beyond that the Jenkins was very slow while plugin was installed. 

![image](https://user-images.githubusercontent.com/50126889/220144049-75d366c3-31c9-41a7-9944-b59a1d57324f.png)

![image](https://user-images.githubusercontent.com/50126889/220144142-fcec6a52-baef-4c6f-828a-27ea9fb2012f.png)

**Comment by eliaquimmauricio** [comment]
Nice !! It works ! :D 

Thank you.
