### ISSUE TITLE
Darken warning panel background color

### ISSUE THREAD

**Issue by lppedd** [jenkinsci/dark-theme-plugin#337]
Example:

![image](https://user-images.githubusercontent.com/19871649/224118770-2fed8933-b618-44d7-b236-8004c8d1c695.png)

This is basically a punch in the eyes. Too bright imo.  
Plus, the white text is not readable.

Jenkins LTS 2.387.1

**Comment by TripleStarCodeHunter** [comment]
Could you provide further details, please? Are you only seeking to darken the orange color to better complement the overall UI and text, or do you also want to modify other colors? 
Additionally, can you assign me this issue?

**Comment by timja** [comment]
This was fixed in 2.453 https://github.com/jenkinsci/jenkins/pull/9115:

<img width="642" alt="image" src="https://github.com/user-attachments/assets/6f505e37-329e-4533-a321-eefd1755c4e1">
