### ISSUE TITLE
Dark mode is broken in console view

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/dark-theme-plugin#392]
Using version 359.vb_d6175e5f6f9 on 2.421 creates an unreadable console pattern:

![Screenshot 2023-08-30 at 23 20 29](https://github.com/jenkinsci/dark-theme-plugin/assets/13383509/351d1586-c6fa-401b-9883-be56866c7751)

**Comment by zbynek** [comment]
@NotMyFault is this still reproducible somewhere? Checking some console outputs on ci.jenkins.io ([example](https://ci.jenkins.io/job/Core/job/jenkins/job/master/5641/console)) does not show this problem in Chrome.

**Comment by NotMyFault** [comment]
> @NotMyFault is this still reproducible somewhere? Checking some console outputs on ci.jenkins.io ([example](https://ci.jenkins.io/job/Core/job/jenkins/job/master/5641/console)) does not show this problem in Chrome.

Looks fine on ci.j. I guess this was fixed in a recent release.
