### ISSUE TITLE
dark theme option missing

### ISSUE THREAD

**Issue by SagarRawat24** [jenkinsci/dark-theme-plugin#447]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

window 11 but i m using ec2 instance which is based on ubuntu 

### Reproduction steps

after installing the dark theme i cant see built in theme option in system configure dark theme is enable in pulgins i also re-install but nothing is working 

### Expected Results

show the option of theme or built in theme in system configure

### Actual Results

![Screenshot (10)](https://github.com/jenkinsci/dark-theme-plugin/assets/116507833/9eeac957-183d-44c0-9d51-45ea7000a849)

**Comment by zbynek** [comment]
New versions of Jenkins have the theme setting  under *Manage Jenkins > Appearance* instead of *Manage Jenkins > System*.
