### ISSUE TITLE
Folder view ?

### ISSUE THREAD

**Issue by flynet** [jenkinsci/dark-theme-plugin#469]
### Jenkins and plugins versions report
Jenkins 2.426.2

Folder Listing Section on Dashboard looks weird 

### What Operating System are you using (both controller, and any agents involved in the problem)?

![изображение_2024-02-28_202120626](https://github.com/jenkinsci/dark-theme-plugin/assets/1836148/9a3760e1-9bf8-46e1-91e6-f0e777bd1528)

### Reproduction steps

-

### Expected Results

-

### Actual Results

-

**Comment by timja** [comment]
Which plugin is this and how is it configured?

**Comment by flynet** [comment]
Sorry, almost forgot this is not buildin feature 
This is https://plugins.jenkins.io/cloudbees-folder/
Adds Folder Listing Section

**Comment by flynet** [comment]
Please disregard, I see from log, many of plugins incompatible.
