### ISSUE TITLE
hsl instead of hsla

### ISSUE THREAD

**Issue by FedericoTorselloACSoftware** [jenkinsci/dark-theme-plugin#477]
https://github.com/jenkinsci/dark-theme-plugin/blob/808698adccaef519602c407b28cafa00103028ad/src/main/frontend/main.scss#L57

**Comment by timja** [comment]
Why?

**Comment by timja** [comment]
From what I can tell it is available: https://sass-lang.com/documentation/modules/#hsl

**Comment by FedericoTorselloACSoftware** [comment]
Very interesting, it would seem to be an elevation. 
I tried it on https://playcode.io/scss and this is the result:
![image](https://github.com/jenkinsci/dark-theme-plugin/assets/97111707/a5b4f2d1-bcc0-44bd-9a4d-4d4c7186345d)

I would like to thank you and as far as I'm concerned the issue can be closed
