### ISSUE TITLE
JCasC Config Page: Dark Theme is not applied to the non-production-ready warning

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/dark-theme-plugin#61]
![image](https://user-images.githubusercontent.com/3000480/83312925-7ab5c580-a214-11ea-9f6f-1be923281b1e.png)

**Comment by timja** [comment]
What do you mean / expect here?

Currently we aren't changing any of the alert colours from the standard ones

it doesn't seem too bright for me

Do others have any opinion?

**Comment by daniel-beck** [comment]
I filed #102 and only now discovered this. I think these colors are too bright.

**Comment by timja** [comment]
Closing in favour of https://github.com/jenkinsci/dark-theme-plugin/issues/102 which covers all alert colours
