### ISSUE TITLE
Cloudbees health plugin styles conflict with dark theme

### ISSUE THREAD

**Issue by timja** [jenkinsci/dark-theme-plugin#79]
![image](https://user-images.githubusercontent.com/21194782/83732686-53139280-a644-11ea-9d41-27ee9faaa969.png)

likely it's the bootstrap css that's loaded here:
https://github.com/jenkinsci/cloudbees-jenkins-advisor-plugin/blob/master/src/main/resources/com/cloudbees/jenkins/plugins/advisor/AdvisorGlobalConfiguration/index.jelly#L7

cc @oleg-nenashev @aheritier

**Comment by aheritier** [comment]
Effectively @timja 
Not sure if the bug should be reported here or in the Health Advisor plugin. 
Is there any recommandation to avoid such kind of conflict between css ?

**Comment by timja** [comment]
> Effectively @timja
> Not sure if the bug should be reported here or in the Health Advisor plugin.
> Is there any recommandation to avoid such kind of conflict between css ?

health advisor really as this theme just modifies the core colours with variables, but we're just aggregating issues here before reporting them out.

My suggestion would be not to use bootstrap as its invasive and doesn't quite match the rest of Jenkins styles,

The font on the Health advisor page appears to be slightly different to the rest of Jenkins, especially noticeable in the breadcrumbs but also in the sidebar.

Is there something specifically you're using bootstrap for?

cc @fqueiruga

**Comment by aheritier** [comment]
@timja honestly I don't remember, I did it many months ago.
I think it was mainly for the panels.
I can probably do without it but I am pretty sure that I did like often and took the example on another plugin :-)
I know that there is a JEP to improve the Jenkins UI but I didn't follow it a lot. If I can get some guides about what to do / not do to be a good jenkins citizen I'll do it with pleasure cc @oleg-nenashev

**Comment by fqueiruga** [comment]
I don't see any components that make bootstrap needed. Jenkins already has `.alert-*` classes builtin. Removing bootstrap is always a positive :D

**Comment by aheritier** [comment]
I opened https://issues.jenkins-ci.org/browse/JENKINS-62739 to followup

**Comment by aheritier** [comment]
PR in review : https://github.com/jenkinsci/cloudbees-jenkins-advisor-plugin/pull/60

**Comment by timja** [comment]
fixed by above, nice work!
