### ISSUE TITLE
Pipeline stage view difficult to read

### ISSUE THREAD

**Issue by pbradly** [jenkinsci/dark-theme-plugin#85]
The pipeline stage is difficult to read when the dark theme is applied as some of the text is fuzzy and it looks like the dark theme hasn't been applied to the date and time;

<img width="904" alt="Screen Shot 2020-06-06 at 12 24 11" src="https://user-images.githubusercontent.com/11042532/83949317-0ae5a300-a7f1-11ea-8533-8ccfa774209c.png">

I am unsure if this is an issue with the pipeline stage plugin or the dark theme.

**Comment by timja** [comment]
It’s pipeline stage view that needs work done

Thanks for the report, we were aware of the issue but weren’t currently tracking it

**Comment by vikas027** [comment]
Looks like this used to work earlier. There is a nice [screenshot](https://cd.foundation/wp-content/uploads/sites/78/2020/07/darkpipelinepreview.png) in this [blog](https://cd.foundation/blog/2020/08/04/introducing-the-jenkins-dark-theme/).

**Comment by timja** [comment]
@vikas027 the screenshot in the blog uses the pre release version.

The fix has been merged for a week or two but hasn’t been released

**Comment by pbradly** [comment]
@timja is there any time line for when it will be released? I can see the pull request has been merged into master for pipeline stage view plugin.

**Comment by timja** [comment]
I've asked about it: https://github.com/jenkinsci/pipeline-stage-view-plugin/pull/87#issuecomment-669948486

**Comment by timja** [comment]
Released in https://github.com/jenkinsci/pipeline-stage-view-plugin/releases/tag/pipeline-stage-view-2.14

**Comment by pbradly** [comment]
It looks like this update has introduced a bug, as when users are not using dark mode and go to check the logs of a stage, the dark mode colouring is applied;
![Screen Shot 2020-08-14 at 11 31 49](https://user-images.githubusercontent.com/11042532/90266469-0c9b9a80-de22-11ea-96df-98a7c4bfd32b.png)

**Comment by timja** [comment]
It's not actually dark mode but there was possibly a colour reset that was removed there.

Should be a small fix
