### ISSUE TITLE
Build History widget difficult to read

### ISSUE THREAD

**Issue by major-fire** [jenkinsci/dark-theme-plugin#88]
The Build History widget in the left-hand pane is very difficult to read (@v0.0.2) - the font is quite low-weight and doesn't provide a lot of contrast against the background. A heavier-weighted font would be easier to read. 

Difficult to read:
![image](https://user-images.githubusercontent.com/52540488/84158396-bc8c0a80-aa63-11ea-854b-af0bd1e26d0f.png)

`font-weight` set to 1000 (top item only for demonstration)
![image](https://user-images.githubusercontent.com/52540488/84158441-c9106300-aa63-11ea-8425-3bd7a1ed260c.png)

**Comment by fqueiruga** [comment]
These are dark links. I think the dark links should have a different colour than the normal ones. I'd suggest `--text-color`.

**Comment by fqueiruga** [comment]
https://github.com/jenkinsci/jenkins/pull/4808 introduces variables for the dark link colours, but maybe this font-weight should be set by normal CSS rules.

**Comment by timja** [comment]
It looks better to me now after https://github.com/jenkinsci/jenkins/pull/4808

![image](https://user-images.githubusercontent.com/21194782/85308019-99704a80-b4a8-11ea-9eef-ed2f2d9a78f8.png)
