### ISSUE TITLE
Job Run page - "Keep this build ..." form has bg-color:white

### ISSUE THREAD

**Issue by fred-vogt** [jenkinsci/dark-theme-plugin#97]
Been testing with this plugin.  Its working great.

But this stands out on the Job Run details page:
![jenkins-keep-this-build-2020-06-19 19-26-05](https://user-images.githubusercontent.com/1837107/85189349-25913080-b263-11ea-9c39-b7d077425ffa.png)
```html
<div style="float:right; background-color:white; z-index: 1; position:relative; margin-left: 1em">
  <form method="post" action="toggleLogKeep" style="margin-top:1em">
    <span class="yui-button yui-submit-button submit-button primary" id="yui-gen6" name="Submit">
      <span class="first-child">
        <button type="button" tabindex="0" id="yui-gen6-button">Keep this build forever</button>
      </span>
    </span>
...
  </form>
  <div style="margin-top:1em">Started 24 sec ago</div>
  <div>Took <a href="/job/{org}/job/{repo}/job/master/buildTimeTrend">11 sec</a></div>
</div>
```

**Comment by timja** [comment]
Thanks, it just needs the background-colour: white removed

**Comment by fred-vogt** [comment]
@timja - looks like this has to be done in core.

```bash
jenkins$ grep -rIn 'background-color:white' * | grep -v css
core/src/main/resources/hudson/model/AbstractBuild/index.jelly:31:
    <div style="float:right; background-color:white; z-index: 1; position:relative; margin-left: 1em">
...
```
* [jenkins - core/src/main/resources/hudson/model/AbstractBuild/index.jelly](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/hudson/model/AbstractBuild/index.jelly#L31)

<img width="1494" alt="Screen Shot 2020-06-20 at 00 35 02" src="https://user-images.githubusercontent.com/1837107/85196268-f04e0800-b28d-11ea-9c10-cc48b770bb51.png">

**Comment by timja** [comment]
Yup feel free to remove it, completely unneeded and weird that it’s there
