### ISSUE TITLE
Calls to action in noJob.jelly aren't looking correct

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/dark-theme-plugin#98]
This seems too bright:

<img width="860" alt="Screenshot" src="https://user-images.githubusercontent.com/1831569/85206325-9008a600-b321-11ea-9b5d-6997585da625.png">

Jenkins 2.241, Dark Theme Plugin 0.0.3

**Comment by fqueiruga** [comment]
This goes hand in hand with https://github.com/jenkinsci/dark-theme-plugin/issues/102 as it basically shares the same variables

**Comment by timja** [comment]
The styling is slightly different on this specific widget I believe.

I patched it a bit in the initial core PR to be readable, but it could be improved more.

**Comment by timja** [comment]
@all-contributors please add @daniel-beck for testing
